/**
 * LoopBack Application
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.LoopBackApplication);
  }
}(this, function(expect, LoopBackApplication) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new LoopBackApplication.IngredientControllerApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('IngredientControllerApi', function() {
    describe('ingredientControllerCount', function() {
      it('should call ingredientControllerCount successfully', function(done) {
        //uncomment below and update the code to test ingredientControllerCount
        //instance.ingredientControllerCount(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('ingredientControllerCreate', function() {
      it('should call ingredientControllerCreate successfully', function(done) {
        //uncomment below and update the code to test ingredientControllerCreate
        //instance.ingredientControllerCreate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('ingredientControllerDeleteById', function() {
      it('should call ingredientControllerDeleteById successfully', function(done) {
        //uncomment below and update the code to test ingredientControllerDeleteById
        //instance.ingredientControllerDeleteById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('ingredientControllerFind', function() {
      it('should call ingredientControllerFind successfully', function(done) {
        //uncomment below and update the code to test ingredientControllerFind
        //instance.ingredientControllerFind(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('ingredientControllerFindById', function() {
      it('should call ingredientControllerFindById successfully', function(done) {
        //uncomment below and update the code to test ingredientControllerFindById
        //instance.ingredientControllerFindById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('ingredientControllerReplaceById', function() {
      it('should call ingredientControllerReplaceById successfully', function(done) {
        //uncomment below and update the code to test ingredientControllerReplaceById
        //instance.ingredientControllerReplaceById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('ingredientControllerUpdateAll', function() {
      it('should call ingredientControllerUpdateAll successfully', function(done) {
        //uncomment below and update the code to test ingredientControllerUpdateAll
        //instance.ingredientControllerUpdateAll(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('ingredientControllerUpdateById', function() {
      it('should call ingredientControllerUpdateById successfully', function(done) {
        //uncomment below and update the code to test ingredientControllerUpdateById
        //instance.ingredientControllerUpdateById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
