/**
 * LoopBack Application
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.LoopBackApplication);
  }
}(this, function(expect, LoopBackApplication) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new LoopBackApplication.MealControllerApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MealControllerApi', function() {
    describe('mealControllerCount', function() {
      it('should call mealControllerCount successfully', function(done) {
        //uncomment below and update the code to test mealControllerCount
        //instance.mealControllerCount(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('mealControllerCreate', function() {
      it('should call mealControllerCreate successfully', function(done) {
        //uncomment below and update the code to test mealControllerCreate
        //instance.mealControllerCreate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('mealControllerDeleteById', function() {
      it('should call mealControllerDeleteById successfully', function(done) {
        //uncomment below and update the code to test mealControllerDeleteById
        //instance.mealControllerDeleteById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('mealControllerFind', function() {
      it('should call mealControllerFind successfully', function(done) {
        //uncomment below and update the code to test mealControllerFind
        //instance.mealControllerFind(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('mealControllerFindById', function() {
      it('should call mealControllerFindById successfully', function(done) {
        //uncomment below and update the code to test mealControllerFindById
        //instance.mealControllerFindById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('mealControllerReplaceById', function() {
      it('should call mealControllerReplaceById successfully', function(done) {
        //uncomment below and update the code to test mealControllerReplaceById
        //instance.mealControllerReplaceById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('mealControllerUpdateAll', function() {
      it('should call mealControllerUpdateAll successfully', function(done) {
        //uncomment below and update the code to test mealControllerUpdateAll
        //instance.mealControllerUpdateAll(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('mealControllerUpdateById', function() {
      it('should call mealControllerUpdateById successfully', function(done) {
        //uncomment below and update the code to test mealControllerUpdateById
        //instance.mealControllerUpdateById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
