/**
 * LoopBack Application
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.LoopBackApplication);
  }
}(this, function(expect, LoopBackApplication) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new LoopBackApplication.RecipeControllerApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('RecipeControllerApi', function() {
    describe('recipeControllerCount', function() {
      it('should call recipeControllerCount successfully', function(done) {
        //uncomment below and update the code to test recipeControllerCount
        //instance.recipeControllerCount(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('recipeControllerCreate', function() {
      it('should call recipeControllerCreate successfully', function(done) {
        //uncomment below and update the code to test recipeControllerCreate
        //instance.recipeControllerCreate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('recipeControllerDeleteById', function() {
      it('should call recipeControllerDeleteById successfully', function(done) {
        //uncomment below and update the code to test recipeControllerDeleteById
        //instance.recipeControllerDeleteById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('recipeControllerFind', function() {
      it('should call recipeControllerFind successfully', function(done) {
        //uncomment below and update the code to test recipeControllerFind
        //instance.recipeControllerFind(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('recipeControllerFindById', function() {
      it('should call recipeControllerFindById successfully', function(done) {
        //uncomment below and update the code to test recipeControllerFindById
        //instance.recipeControllerFindById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('recipeControllerReplaceById', function() {
      it('should call recipeControllerReplaceById successfully', function(done) {
        //uncomment below and update the code to test recipeControllerReplaceById
        //instance.recipeControllerReplaceById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('recipeControllerUpdateAll', function() {
      it('should call recipeControllerUpdateAll successfully', function(done) {
        //uncomment below and update the code to test recipeControllerUpdateAll
        //instance.recipeControllerUpdateAll(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('recipeControllerUpdateById', function() {
      it('should call recipeControllerUpdateById successfully', function(done) {
        //uncomment below and update the code to test recipeControllerUpdateById
        //instance.recipeControllerUpdateById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
