/**
 * LoopBack Application
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.LoopBackApplication);
  }
}(this, function(expect, LoopBackApplication) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new LoopBackApplication.StoredItemControllerApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('StoredItemControllerApi', function() {
    describe('storedItemControllerCount', function() {
      it('should call storedItemControllerCount successfully', function(done) {
        //uncomment below and update the code to test storedItemControllerCount
        //instance.storedItemControllerCount(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('storedItemControllerCreate', function() {
      it('should call storedItemControllerCreate successfully', function(done) {
        //uncomment below and update the code to test storedItemControllerCreate
        //instance.storedItemControllerCreate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('storedItemControllerDeleteById', function() {
      it('should call storedItemControllerDeleteById successfully', function(done) {
        //uncomment below and update the code to test storedItemControllerDeleteById
        //instance.storedItemControllerDeleteById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('storedItemControllerFind', function() {
      it('should call storedItemControllerFind successfully', function(done) {
        //uncomment below and update the code to test storedItemControllerFind
        //instance.storedItemControllerFind(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('storedItemControllerFindById', function() {
      it('should call storedItemControllerFindById successfully', function(done) {
        //uncomment below and update the code to test storedItemControllerFindById
        //instance.storedItemControllerFindById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('storedItemControllerReplaceById', function() {
      it('should call storedItemControllerReplaceById successfully', function(done) {
        //uncomment below and update the code to test storedItemControllerReplaceById
        //instance.storedItemControllerReplaceById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('storedItemControllerUpdateAll', function() {
      it('should call storedItemControllerUpdateAll successfully', function(done) {
        //uncomment below and update the code to test storedItemControllerUpdateAll
        //instance.storedItemControllerUpdateAll(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('storedItemControllerUpdateById', function() {
      it('should call storedItemControllerUpdateById successfully', function(done) {
        //uncomment below and update the code to test storedItemControllerUpdateById
        //instance.storedItemControllerUpdateById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
