/**
 * LoopBack Application
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import IngredientWithRelations from './IngredientWithRelations';

/**
 * The DoseWithRelations model module.
 * @module model/DoseWithRelations
 * @version 1.0.0
 */
class DoseWithRelations {
    /**
     * Constructs a new <code>DoseWithRelations</code>.
     * (Schema options: { includeRelations: true })
     * @alias module:model/DoseWithRelations
     * @param qty {Number} 
     */
    constructor(qty) { 
        
        DoseWithRelations.initialize(this, qty);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, qty) { 
        obj['qty'] = qty;
    }

    /**
     * Constructs a <code>DoseWithRelations</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DoseWithRelations} obj Optional instance to populate.
     * @return {module:model/DoseWithRelations} The populated <code>DoseWithRelations</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DoseWithRelations();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('qty')) {
                obj['qty'] = ApiClient.convertToType(data['qty'], 'Number');
            }
            if (data.hasOwnProperty('recipeId')) {
                obj['recipeId'] = ApiClient.convertToType(data['recipeId'], 'Number');
            }
            if (data.hasOwnProperty('ingredientId')) {
                obj['ingredientId'] = ApiClient.convertToType(data['ingredientId'], 'Number');
            }
            if (data.hasOwnProperty('ingredient')) {
                obj['ingredient'] = IngredientWithRelations.constructFromObject(data['ingredient']);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
DoseWithRelations.prototype['id'] = undefined;

/**
 * @member {Number} qty
 */
DoseWithRelations.prototype['qty'] = undefined;

/**
 * @member {Number} recipeId
 */
DoseWithRelations.prototype['recipeId'] = undefined;

/**
 * @member {Number} ingredientId
 */
DoseWithRelations.prototype['ingredientId'] = undefined;

/**
 * @member {module:model/IngredientWithRelations} ingredient
 */
DoseWithRelations.prototype['ingredient'] = undefined;






export default DoseWithRelations;

