/**
 * LoopBack Application
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The IngredientWithRelations model module.
 * @module model/IngredientWithRelations
 * @version 1.0.0
 */
class IngredientWithRelations {
    /**
     * Constructs a new <code>IngredientWithRelations</code>.
     * (Schema options: { includeRelations: true })
     * @alias module:model/IngredientWithRelations
     * @param name {String} 
     */
    constructor(name) { 
        
        IngredientWithRelations.initialize(this, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name) { 
        obj['name'] = name;
    }

    /**
     * Constructs a <code>IngredientWithRelations</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IngredientWithRelations} obj Optional instance to populate.
     * @return {module:model/IngredientWithRelations} The populated <code>IngredientWithRelations</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IngredientWithRelations();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
IngredientWithRelations.prototype['id'] = undefined;

/**
 * @member {String} name
 */
IngredientWithRelations.prototype['name'] = undefined;






export default IngredientWithRelations;

