/**
 * LoopBack Application
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The IngredientsIdFields model module.
 * @module model/IngredientsIdFields
 * @version 1.0.0
 */
class IngredientsIdFields {
    /**
     * Constructs a new <code>IngredientsIdFields</code>.
     * @alias module:model/IngredientsIdFields
     */
    constructor() { 
        
        IngredientsIdFields.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>IngredientsIdFields</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IngredientsIdFields} obj Optional instance to populate.
     * @return {module:model/IngredientsIdFields} The populated <code>IngredientsIdFields</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IngredientsIdFields();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Boolean');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {Boolean} id
 */
IngredientsIdFields.prototype['id'] = undefined;

/**
 * @member {Boolean} name
 */
IngredientsIdFields.prototype['name'] = undefined;






export default IngredientsIdFields;

