/**
 * LoopBack Application
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MealsIdScope from './MealsIdScope';

/**
 * The MealsIdInclude model module.
 * @module model/MealsIdInclude
 * @version 1.0.0
 */
class MealsIdInclude {
    /**
     * Constructs a new <code>MealsIdInclude</code>.
     * @alias module:model/MealsIdInclude
     */
    constructor() { 
        
        MealsIdInclude.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MealsIdInclude</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MealsIdInclude} obj Optional instance to populate.
     * @return {module:model/MealsIdInclude} The populated <code>MealsIdInclude</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MealsIdInclude();

            if (data.hasOwnProperty('relation')) {
                obj['relation'] = ApiClient.convertToType(data['relation'], 'String');
            }
            if (data.hasOwnProperty('scope')) {
                obj['scope'] = MealsIdScope.constructFromObject(data['scope']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} relation
 */
MealsIdInclude.prototype['relation'] = undefined;

/**
 * @member {module:model/MealsIdScope} scope
 */
MealsIdInclude.prototype['scope'] = undefined;






export default MealsIdInclude;

