/**
 * LoopBack Application
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MealPartial model module.
 * @module model/MealPartial
 * @version 1.0.0
 */
class MealPartial {
    /**
     * Constructs a new <code>MealPartial</code>.
     * (Schema options: { partial: true })
     * @alias module:model/MealPartial
     */
    constructor() { 
        
        MealPartial.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MealPartial</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MealPartial} obj Optional instance to populate.
     * @return {module:model/MealPartial} The populated <code>MealPartial</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MealPartial();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'Date');
            }
            if (data.hasOwnProperty('occasion')) {
                obj['occasion'] = ApiClient.convertToType(data['occasion'], 'String');
            }
            if (data.hasOwnProperty('recipeId')) {
                obj['recipeId'] = ApiClient.convertToType(data['recipeId'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
MealPartial.prototype['id'] = undefined;

/**
 * @member {Date} date
 */
MealPartial.prototype['date'] = undefined;

/**
 * @member {String} occasion
 */
MealPartial.prototype['occasion'] = undefined;

/**
 * @member {Number} recipeId
 */
MealPartial.prototype['recipeId'] = undefined;






export default MealPartial;

