/**
 * LoopBack Application
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The NewRecipe model module.
 * @module model/NewRecipe
 * @version 1.0.0
 */
class NewRecipe {
    /**
     * Constructs a new <code>NewRecipe</code>.
     * (Schema options: { title: &#39;NewRecipe&#39;, exclude: [ &#39;id&#39; ] })
     * @alias module:model/NewRecipe
     * @param name {String} 
     * @param main {String} 
     * @param secondary {String} 
     */
    constructor(name, main, secondary) { 
        
        NewRecipe.initialize(this, name, main, secondary);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, main, secondary) { 
        obj['name'] = name;
        obj['main'] = main;
        obj['secondary'] = secondary;
    }

    /**
     * Constructs a <code>NewRecipe</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/NewRecipe} obj Optional instance to populate.
     * @return {module:model/NewRecipe} The populated <code>NewRecipe</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NewRecipe();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('main')) {
                obj['main'] = ApiClient.convertToType(data['main'], 'String');
            }
            if (data.hasOwnProperty('secondary')) {
                obj['secondary'] = ApiClient.convertToType(data['secondary'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
NewRecipe.prototype['name'] = undefined;

/**
 * @member {String} main
 */
NewRecipe.prototype['main'] = undefined;

/**
 * @member {String} secondary
 */
NewRecipe.prototype['secondary'] = undefined;






export default NewRecipe;

