/**
 * LoopBack Application
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The NewStoredItem model module.
 * @module model/NewStoredItem
 * @version 1.0.0
 */
class NewStoredItem {
    /**
     * Constructs a new <code>NewStoredItem</code>.
     * (Schema options: { title: &#39;NewStoredItem&#39;, exclude: [ &#39;id&#39; ] })
     * @alias module:model/NewStoredItem
     * @param qty {Number} 
     */
    constructor(qty) { 
        
        NewStoredItem.initialize(this, qty);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, qty) { 
        obj['qty'] = qty;
    }

    /**
     * Constructs a <code>NewStoredItem</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/NewStoredItem} obj Optional instance to populate.
     * @return {module:model/NewStoredItem} The populated <code>NewStoredItem</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NewStoredItem();

            if (data.hasOwnProperty('qty')) {
                obj['qty'] = ApiClient.convertToType(data['qty'], 'Number');
            }
            if (data.hasOwnProperty('ingredientId')) {
                obj['ingredientId'] = ApiClient.convertToType(data['ingredientId'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} qty
 */
NewStoredItem.prototype['qty'] = undefined;

/**
 * @member {Number} ingredientId
 */
NewStoredItem.prototype['ingredientId'] = undefined;






export default NewStoredItem;

