/**
 * LoopBack Application
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RecipesIdFields model module.
 * @module model/RecipesIdFields
 * @version 1.0.0
 */
class RecipesIdFields {
    /**
     * Constructs a new <code>RecipesIdFields</code>.
     * @alias module:model/RecipesIdFields
     */
    constructor() { 
        
        RecipesIdFields.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RecipesIdFields</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RecipesIdFields} obj Optional instance to populate.
     * @return {module:model/RecipesIdFields} The populated <code>RecipesIdFields</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RecipesIdFields();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Boolean');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'Boolean');
            }
            if (data.hasOwnProperty('main')) {
                obj['main'] = ApiClient.convertToType(data['main'], 'Boolean');
            }
            if (data.hasOwnProperty('secondary')) {
                obj['secondary'] = ApiClient.convertToType(data['secondary'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {Boolean} id
 */
RecipesIdFields.prototype['id'] = undefined;

/**
 * @member {Boolean} name
 */
RecipesIdFields.prototype['name'] = undefined;

/**
 * @member {Boolean} main
 */
RecipesIdFields.prototype['main'] = undefined;

/**
 * @member {Boolean} secondary
 */
RecipesIdFields.prototype['secondary'] = undefined;






export default RecipesIdFields;

