/**
 * LoopBack Application
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The StoredItemPartial model module.
 * @module model/StoredItemPartial
 * @version 1.0.0
 */
class StoredItemPartial {
    /**
     * Constructs a new <code>StoredItemPartial</code>.
     * (Schema options: { partial: true })
     * @alias module:model/StoredItemPartial
     */
    constructor() { 
        
        StoredItemPartial.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>StoredItemPartial</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/StoredItemPartial} obj Optional instance to populate.
     * @return {module:model/StoredItemPartial} The populated <code>StoredItemPartial</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StoredItemPartial();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('qty')) {
                obj['qty'] = ApiClient.convertToType(data['qty'], 'Number');
            }
            if (data.hasOwnProperty('ingredientId')) {
                obj['ingredientId'] = ApiClient.convertToType(data['ingredientId'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
StoredItemPartial.prototype['id'] = undefined;

/**
 * @member {Number} qty
 */
StoredItemPartial.prototype['qty'] = undefined;

/**
 * @member {Number} ingredientId
 */
StoredItemPartial.prototype['ingredientId'] = undefined;






export default StoredItemPartial;

